name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests with coverage
        run: npm run test:unit -- --coverage

      - name: Enforce coverage ≥ 80%
        run: |
          pct=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          echo "Line coverage: $pct%"
          awk "BEGIN{exit ($pct<80)}"

      - name: Integration tests
        run: npm run test:integration

      - name: Generate SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom/sbom.json

      - name: Dependency scan (Snyk)
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  regression:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Run nightly regression
        run: npm run test:regression
